### PR TITLE
Chromeheadless

### LINKED ISSUE #293: PhantomJS is abandoned, replace it with Selenium/Chrome headless
related https://github.com/rails/rails/pull/30930/

### PR DESCRIPTION
**Pull request by stoivo**
close #293 

I added a Chrome headless runner. I tries to add it without adding any other run depenecies at installation. "chrome_remote" is a gem I require at runtime if you use chrome headless.

I left the default at :phanthonJS
We will start to run our CI jobs on chrome today. I want to start the process of getting this meged.

### CODE REVIEW

**Comment by agvald** [comment]
I've looked over the code and it seams good to me.

**Comment by kazooiebombchu** [comment]
I would really like to have this feature too at the moment. Any news when this is gonna be merged?

**Comment by stoivo** [comment]
> I would really like to have this feature too at the moment. Any news when this is gonna be merged?

I don't know but I would love to have someone else test it as well.
You can add this to your Gemfile and try it out 
```
  gem "chrome_remote"
  gem "jasmine", git: "https://github.com/stoivo/jasmine-gem.git", branch: "chromeheadless"
```

**Comment by stoivo** [comment]
ping @slackersoft

**Comment by slackersoft** [comment]
I think this looks pretty good from an organizational perspective, but I'm not seeing any tests at all for the Chrome runner. I'd like to see most of the integration tests that actually run `rake jasmine:ci` to be run with both PhantomJS and Chrome, but I need at least a couple of spot checks to make sure it doesn't get broken going forward. We'll want to make sure the `.travis.yml` is updated to bring in the [Travis chrome addon](https://docs.travis-ci.com/user/chrome)

**Comment by stoivo** [comment]
I havn't looked to much but you we have some integrations spec for PhantomJS I can copy?

**Comment by stoivo** [comment]
I copid the the 4 most basic spec for PhansomJS and now they run with Chrome Headless. I think there is's much to gain by porting all the other too.
@slackersoft What do you think? Are we ready for a merge and a new release?

**Comment by stoivo** [comment]
ping @slackersoft

**Comment by stoivo** [comment]
Do you think the featuer is worth a release?

**Comment by jamesyesware** [comment]
Our company is also switching over to running our Jasmine specs with ChromeHeadless. Any updates on a release with this? Seems like it'll make the switch a bit easier. If it'll be a little while, we can find an alternate way forward for now.

**Comment by stoivo** [comment]
@jamesyesware I have some error with my spec suite, One of the fixes need to be applied here. Probably not this week nor next but the one after. 

I would we very happy if you could try out chrome. You could tri it by changing you gemfile to 
```
gem "jasmine", git: "https://github.com/stoivo/jasmine-gem.git", branch: "chromeheadless"
```

**Comment by stoivo** [comment]
I have make an other PR with by changes so it works better with Jquery object in execeptions.

**Pull request merged**
